# Definitions

A Euclidean minimum spanning tree (MST) connects *n* data points
via *n-1* shortest segments.  It is a connected acyclic graph where:

* vertices represent the points,
* edges are weighted by the distances between point pairs,
* edges have minimal total weight.

The `mst_euclid` function determines the classic
Euclidean minimum spanning trees as well as ones
corresponding to mutual reachability distances {cite}`hdbscan`.


MSTs can be used in topological data analysis
(clustering, density estimation, dimensionality reduction,
outlier detection, etc.); see:
[**hdbscan**](https://hdbscan.readthedocs.io/en/latest/),
[**deadwood**](https://deadwood.gagolewski.com/),
[**genieclust**](https://genieclust.gagolewski.com/), and
[**lumbermark**](https://lumbermark.gagolewski.com/).


::::{note}
This section is a work in progress.

In the meantime, take a look at the
[Python](../pythonapi) or
[R](../rapi)
package reference manual.
::::


Relevant citations —
the Jarník-Prim algorithm: {cite}`jarnik`, {cite}`olson`, {cite}`prim`,
the Borůvka algorithm: {cite}`boruvka`, {cite}`dualtreeboruvka`,
K-d trees: {cite}`kdtrees`, {cite}`kdtreesmidrange`, {cite}`kdtreesoptim`,
mutual reachability distance: {cite}`hdbscan`, {cite}`hdbscan2`.

