name: quitefastmst wheels

on: workflow_dispatch

env:
    CIBW_SKIP: cp36-* cp37-* cp38-* *-win32
    CIBW_ARCHS: all
    PYTHONUTF8: 1
    #*-win32 *-musllinux* *-macosx_*_universal2* *win_arm64* *-manylinux_arm64 *-manylinux_i686 *-manylinux_ppc64le *-manylinux_s390x *-manylinux_aarch64
    # TODO: manylinux aarch64
    # TODO: macos arm64
    #CIBW_TEST_SKIP: "*-macosx_arm64"
    #CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux' && runner.arch == 'X64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - uses: actions/setup-python@v5
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.1
        env:
          # https://cibuildwheel.pypa.io/en/stable/faq/#emulation
          CIBW_ARCHS_LINUX: ${{ runner.arch == 'X64' && 'auto ppc64le s390x' || 'auto' }}

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
